name: Release Windows

on:
  workflow_dispatch:
  release:
    types: published

env:
  PACKAGE: ${{ github.event.repository.name }}

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v4

    - name: 'Dependencies: Nix'
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v4

    - name: Build
      env:
        NIXPKGS_ALLOW_BROKEN: 1
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
      run: nix build -L --no-update-lock-file --show-trace --impure .#${{ env.PACKAGE }}Mingw64Zip

    - name: Extract informations
      id: extract
      shell: bash
      run: |
        echo "upload_url=$(curl -sL ${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}} | jq -r '.upload_url')" >> $GITHUB_OUTPUT

    - name: Deploy .zip on Github
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.extract.outputs.upload_url }}
        asset_path: result/${{ env.PACKAGE }}-x86_64-w64-mingw32-${{ github.ref_name }}.zip
        asset_name: ${{ env.PACKAGE }}-${{ github.ref_name }}-x86_64-w64-mingw32.zip
        asset_content_type: application/zip

    - name: Fail
      if: ${{ github.event_name != 'release' }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed("Trigger event: ${{ github.event_name }} (should be release), Git ref: ${{ github.ref_name }}")
